=== alanbijuthomas/Stendhal/data/conf/achievements.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="stendhal"
	xmlns:tns="http://www.example.org/zones" elementFormDefault="qualified"
	xmlns:Q1="stendhal">
	
	<element name="achievements" type="Q1:Achievements"></element>
		
	<complexType name="Achievements" >
		<sequence>
			<element name="achievement" type="Q1:Achievement" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
	
	<complexType name="Achievement">
		<sequence>
			<element name="title" type="string" />
			<element name="category" type="string" />
			<element name="description" type="string" />
			<element name="basescore" type="int" />
			<element name="active" type="string" />
			<element name="condition" type="Q1:Condition" />
		</sequence>
		<attribute name="identifier" type="string" use="required"/>
	</complexType>
	
	<complexType name="Condition">
		<sequence minOccurs="0" maxOccurs="unbounded">
			<element name="argument" type="anyType"/>
		</sequence>
		<attribute name="constructor" type="string"></attribute>
	</complexType>
	
</schema>

=== alanbijuthomas/Stendhal/data/conf/achievements/fighting.xml
<?xml version="1.0" encoding="UTF-8"?>
<achievements xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../achievements.xsd ">

<achievement identifier="fight.general.rats">
	<title>Rat Hunter</title>
	<category>Fighting</category>
	<description>Kill 15 rats</description>
	<basescore>1</basescore>
	<active>yes</active>
	<condition constructor="PlayerHasKilledNumberOfCreaturesCondition">
		<argument>rat</argument>
		<argument>15</argument>
	</condition>
</achievement>

<achievement identifier="fight.general.exterminator">
	<title>Exterminator</title>
	<category>Fighting</category>
	<description>Kill 10 rats of each kind</description>
	<basescore>2</basescore>
	<active>yes</active>
	<condition constructor="PlayerHasKilledNumberOfCreaturesCondition">
		<argument>10</argument>
		<argument>rat</argument>
		<argument>caverat</argument>
		<argument>razorrat</argument>
		<argument>venomrat</argument>
		<argument>zombie rat</argument>
		<argument>giantrat</argument>
		<argument>ratman</argument>
		<argument>ratwoman</argument>
		<argument>archrat</argument>
	</condition>
</achievement>

<achievement identifier="fight.general.deer">
	<title>Deer Hunter</title>
	<category>Fighting</category>
	<description>Kill 25 deer</description>
	<basescore>1</basescore>
	<active>yes</active>
	<condition constructor="PlayerHasKilledNumberOfCreaturesCondition">
		<argument>deer</argument>
		<argument>25</argument>
	</condition>
</achievement>

<achievement identifier="fight.general.boars">
	<title>Boar Hunter</title>
	<category>Fighting</category>
	<description>Kill 20 boar</description>
	<basescore>1</basescore>
	<active>yes</active>
	<condition constructor="PlayerHasKilledNumberOfCreaturesCondition">
		<argument>boar</argument>
		<argument>20</argument>
	</condition>
</achievement>

<achievement identifier="fight.general.bears">
	<title>Bear Hunter</title>
	<category>Fighting</category>
	<description>Kill 10 black bears, 10 bears and 10 babybears</description>
	<basescore>1</basescore>
	<active>yes</active>
	<condition constructor="PlayerHasKilledNumberOfCreaturesCondition">
		<argument>10</argument>
		<argument>bear</argument>
		<argument>black bear</argument>
		<argument>babybear</argument>
	</condition>
</achievement>

<achievement identifier="fight.general.foxes">
	<title>Fox Hunter</title>
	<category>Fighting</category>
	<description>Kill 20 foxes</description>
	<basescore>1</basescore>
	<active>yes</active>
	<condition constructor="PlayerHasKilledNumberOfCreaturesCondition">
		<argument>fox</argument>
		<argument>20</argument>
	</condition>
</achievement>

<achievement identifier="fight.general.ents">
	<title>Wood Cutter</title>
	<category>Fighting</category>
	<description>Kill 10 ents, 10 entwifes and 10 old ents</description>
	<basescore>2</basescore>
	<active>yes</active>
	<condition constructor="PlayerHasKilledNumberOfCreaturesCondition">
		<argument>10</argument>
		<argument>ent</argument>
		<argument>entwife</argument>
		<argument>old ent</argument>
	</condition>
</achievement>

<achievement identifier="fight.special.rare">
	<title>Poacher</title>
	<category>Fighting</category>
	<description>Kill any rare creature</description>
	<basescore>5</basescore>
	<active>yes</active>
	<condition constructor="KilledRareCreatureCondition"></condition>
</achievement>

<achievement identifier="fight.special.all">
	<title>Legend</title>
	<category>Fighting</category>
	<description>Kill all creatures solo</description>
	<basescore>5</basescore>
	<active>yes</active>
	<condition constructor="KilledSoloAllCreaturesCondition"></condition>
</achievement>

<achievement identifier="fight.special.allshared">
	<title>Team Player</title>
	<category>Fighting</category>
	<description>Kill all creatures in a team</description>
	<basescore>5</basescore>
	<active>yes</active>
	<condition constructor="KilledSharedAllCreaturesCondition"></condition>
</achievement>

</achievements>
